"""add_updated_at_to_post_comment

Revision ID: 943d6fcbdbc3
Revises: 2025_07_26_1200
Create Date: 2025-07-26 12:46:05.344178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "943d6fcbdbc3"
down_revision = "2025_07_21_1640"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postcomment', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postcomment', 'updated_at')
    # ### end Alembic commands ###
