"""update_industry_enum_to_181_industries

Revision ID: d2505fe414dd
Revises: 943d6fcbdbc3
Create Date: 2025-08-04 15:44:42.520490

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d2505fe414dd"
down_revision = "943d6fcbdbc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
