"""add_missing_columns_for_company_and_mentions

Revision ID: 061beb4f2f31
Revises: 4a64a256109e
Create Date: 2025-08-08 19:54:05.179723

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "061beb4f2f31"
down_revision = "4a64a256109e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing columns to company table
    op.add_column('company', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('user_id', sa.String(), nullable=True))
    
    # Add missing column to post table
    op.add_column('post', sa.Column('company_id', sa.String(), nullable=True))
    
    # Add missing column to postmention table
    op.add_column('postmention', sa.Column('mention_type', sa.String(length=50), nullable=True, server_default='direct'))
    
    # Add foreign key constraints
    op.create_foreign_key('fk_company_user_id', 'company', 'user', ['user_id'], ['id'])
    op.create_foreign_key('fk_post_company_id', 'post', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints
    op.drop_constraint('fk_post_company_id', 'post', type_='foreignkey')
    op.drop_constraint('fk_company_user_id', 'company', type_='foreignkey')
    
    # Drop columns
    op.drop_column('postmention', 'mention_type')
    op.drop_column('post', 'company_id')
    op.drop_column('company', 'user_id')
    op.drop_column('company', 'company_size')
    # ### end Alembic commands ###
