"""update_industry_enum_with_181_specific_industries

Revision ID: c0ec106d81ce
Revises: d2505fe414dd
Create Date: 2025-08-04 16:05:39.821353

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0ec106d81ce"
down_revision = "d2505fe414dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
