"""add_indexes_to_post_mention_table

Revision ID: 1047f7cf01a8
Revises: 061beb4f2f31
Create Date: 2025-08-09 10:11:07.852953

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "1047f7cf01a8"
down_revision = "061beb4f2f31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_mention",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("post_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "mentioned_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "mentioned_by_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("mention_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position_start", sa.Integer(), nullable=False),
        sa.Column("position_end", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mentioned_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mentioned_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_post_mention_created_at", "post_mention", ["created_at"], unique=False
    )
    op.create_index(
        "ix_post_mention_mentioned_by_user_id",
        "post_mention",
        ["mentioned_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_post_mention_mentioned_user_id",
        "post_mention",
        ["mentioned_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_post_mention_post_date",
        "post_mention",
        ["post_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_post_mention_post_id", "post_mention", ["post_id"], unique=False
    )
    op.create_index(
        "ix_post_mention_user_date",
        "post_mention",
        ["mentioned_user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_post_mention_user_date", table_name="post_mention")
    op.drop_index("ix_post_mention_post_id", table_name="post_mention")
    op.drop_index("ix_post_mention_post_date", table_name="post_mention")
    op.drop_index("ix_post_mention_mentioned_user_id", table_name="post_mention")
    op.drop_index("ix_post_mention_mentioned_by_user_id", table_name="post_mention")
    op.drop_index("ix_post_mention_created_at", table_name="post_mention")
    op.drop_table("post_mention")
    # ### end Alembic commands ###
