"""add_updated_at_to_post_comment

Revision ID: c6732f81c2a8
Revises: 2025_07_21_1640
Create Date: 2025-07-26 11:51:51.524447

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6732f81c2a8"
down_revision = "2025_07_21_1640"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
